### PR TITLE
relax typer version

### PR DESCRIPTION
**Pull request by bonastreyair**
When using the package only typer version 0.9.x is compatible along with this package making it very strict when installed in a single project.

New releases of typer have been released so this is just an update to relax the typer version to allow for future versions.

### CODE REVIEW

**Review by ronenlu — APPROVED** [review]

**Comment by bonastreyair** [comment]
mysql tests are not passing due to a logging problem (unrelated to the proposed changes)

What should I do to ensure all tests pass?

**Comment by ronenlu** [comment]
Thank you @bonastreyair!
I cannot merge your PR, because your repo is lacking necessary secrets, but I copied your commit and merged it.
The latest version in of the provider will have more relaxed versioning  thanks to you.

**Comment by bonastreyair** [comment]
@ronenlu, when it is expected to have the next release so that it can be actually usable from pypi?

**Comment by ronenlu** [comment]
> @ronenlu, when it is expected to have the next release so that it can be actually usable from pypi?

@bonastreyair the change is released: https://pypi.org/project/atlas-provider-sqlalchemy/

**Pull request closed without merging**
